services:
    form.route_extension:
        class: Havvg\Bundle\DRYBundle\Form\Extension\RouteExtension
        arguments:
            - '@router'
        tags:
            - { name: 'form.type_extension', extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType' }
