security:
    encoders:
# Remove this encoder, see example below.
        Symfony\Component\Security\Core\User\User: plaintext
#        Application\Model\User:
#            algorithm: bcrypt
#            cost: %bcrypt.cost%

    providers:
        # Replace this provider with an actual user provider.
        in_memory:
            memory:
                users:
                    tester:
                        password: testpass
                        roles: 'ROLE_USER'

# Define the service.
#        application:
#            id: user.provider

    firewalls:
        dev:
            pattern:  ^/_(profiler|wdt|error)/
            security: false

# In case the "app" firewall is not accessible anonymously, allow access to the login route.
#        login:
#            pattern: ^/login$
#            anonymous: true

        app:
            pattern: ^/

            anonymous: ~

# Secure the whole application.
#            pattern: ^/
            form_login:
                # Define the routes below
                login_path: security_login
                check_path: security_login_check

                username_parameter: login[username]
                password_parameter: login[password]
                csrf_parameter:     login[_token]

                use_referer:  true
                default_target_path: /

            remember_me:
                secret: %remember_me_secret%
                name: remember-me
                remember_me_parameter: login[remember_me]

            logout:
                path: security_logout
                target: /

    access_control:
        -
            path: ^/_fragments
            ip: 127.0.0.1
